spring:
  redis:
    host: localhost
    port: 8989

ustawienia:
  numerIndeksu: 434871
  wycena: "CENY_BEZ_ZMIAN"
  zamowienia: "POJEDYNCZE"
  zaopatrzenie: "GRUPOWE"
  wydarzenia: "RAPORT_SPRZEDAŻY"
  liczbaZadan: 200
